name = "template_name"
version = "1.0.0"
type = "text"
production_host = "silver-donkey-gertrudis-u7lvotea.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "template_name_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "template_name.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeigv5m6rvwla53wj5jfwg6i27ddnmtspsiaobmw3zhhnyf7oekvvle"
created = "2025-05-31T00:23:18.432Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "5782bdd012fcf8f2ae073c45c3e2a42a3b8794b7cf5913f17bfb0ee7bf6e9495"
