name = "template_name"
version = "1.0.0"
type = "text"
production_host = "silver-donkey-gertrudis-u7lvotea.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "template_name_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "template_name.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeidobmrdrmoxwwsmvfsm4rskxc23ijiljgocwbigg3wd2mryqd3zmm"
created = "2025-05-31T18:38:06.972Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "075807b756564c329cf753d96844482794d4e245e86c8751ba721cc07292427b"
