name = "template_name"
version = "1.0.0"
type = "text"
production_host = "silver-donkey-gertrudis-u7lvotea.bls.dev"

[deployment]
permission = "public"
nodes = 1
permissions = [ "https://ruta.up.railway.app" ]

[build]
dir = "build"
entry = "template_name_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "template_name.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeigh2lhapwlr6zveufnjoly5fkrajr4gfpaws5ffrmnpdnduwk2lfi"
created = "2025-05-31T19:16:16.550Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "70fc93ced3deaca50b7d40164c854163ed7493ff4802e6b233957702367990d5"
